#!/bin/bash
pkg update -y
pkg upgrade -y
pkg install git -y
pkg install python -y
pkg install clang -y
pkg install make -y
pkg install curl -y
pkg install wget -y
pkg install vim -y
pkg install openssh -y
pkg install unzip -y
pkg install zip -y
pkg install tar -y
pkg install bash -y
pkg install ffmpeg -y
pkg install nodejs -y
pkg install npm -y
pkg install ruby -y
pkg install perl -y
pkg install htop -y
pkg install screen -y
pkg install neofetch -y
pkg install termux-tools -y
pkg install proot-distro -y
pkg install fish -y
pkg install zsh -y
pkg install tmux -y
pkg install libcrypt-dev -y
pkg install libssl-dev -y
pkg install libffi-dev -y
pkg install libsqlite-dev -y
pkg install libjpeg-turbo -y
pkg install libxml2 -y
pkg install libxslt -y
pkg install gettext -y
pkg install jq -y
pkg install ncdu -y
pkg install wget -y
pkg install tar -y
pkg install socat -y
pkg install dnsutils -y
pkg install lsof -y
pkg install strace -y
pkg install procps -y
pkg install tshark -y
pkg install sysstat -y
pkg install iputils -y
pkg install nmap -y
pkg install tmux -y
pkg install clang -y
pkg install cmake -y
pkg install gdb -y
pkg install binutils -y
pkg install patch -y
pkg install bzip2 -y
pkg install util-linux -y
pkg install zip -y
pkg install openssl -y
pkg install texinfo -y
pkg install sqlite -y
pkg install zlib -y
pkg install lua -y
pkg install bc -y
pkg install cmake -y
pkg install php -y
pkg install dnsutils -y
pkg install clang -y
